title: Page

pages: 
	template:
    - default
    - textelong
    - souspage
files: true

fields:
  title:
    label: Titre
    type:  text
  cover: 
    label: Image à afficher en photo de couverture
    type: selector
    mode: single
  text:
    label: Texte
    type: markdown
  displayQuotes: 
    label: Afficher les citations dans les définitions ? 
    type: radio
    options: 
      oui: oui
      non: non
    default: oui 